### ISSUE TITLE
A few minor suggestions for the documentation

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Sparkle#106]
I was following these instructions to install Sparkle on my MacBook (Monterey). https://github.com/GemTalk/Sparkle/blob/main/Documentation/SparkleInstall.pdf
Here are a few suggestions: 

- “Edit loginSystemUser.topaz”  - Might want to give a sample of how to add a netldi. I didn't see one in the default login files in Sparkle. Perhaps in the file itself. 
- Might be helpful to provide a link to the gemstone documentation on installing / starting gemstone. 
- "3. Open a Pharo Playground ... and execute"  - I believe that Pharo uses "Do it" instead of execute. 
- Why is `UnprivilegedUser` the default in the login.topaz file? Why not save the user a step and make it DataCurator?
- I had forgotten that evaluating an expression in the sparkle evaluator pane required Command-S on my mac. Might want to add some documentation that makes it easy for the user to realize they have to press Command-S to do something. 
- Once a user logs in, having a link to the instructions for how to use the product would be helpful - 
Maybe just include a link in the docs … “after successfully logging in go <here> to do stuff”

**Comment by martinmcclure** [comment]
Changes are pushed to the development branch, as summarized below.

>“Edit loginSystemUser.topaz” - Might want to give a sample of how to add a netldi. I didn't see one in the default login files in Sparkle. Perhaps in the file itself.

The installation script never uses a netldi, so the user only needs to do the edits specified.
>Might be helpful to provide a link to the gemstone documentation on installing / starting gemstone.

Links to documentation of past versions added. Can't link to GS docs for the required 3.7 version, since those docs haven't yet been written.
>"3. Open a Pharo Playground ... and execute" - I believe that Pharo uses "Do it" instead of execute.

Now references "Do it."
>Why is UnprivilegedUser the default in the login.topaz file? Why not save the user a step and make it DataCurator?

Removed the "DataCurator" example from the text. DataCurator is quite privileged -- the intent here was to say that you don't need any privileges at all, and which user is their choice.
>I had forgotten that evaluating an expression in the sparkle evaluator pane required Command-S on my mac. Might want to add some documentation that makes it easy for the user to realize they have to press Command-S to do something.

Changed the text to instead of saying "Ctrl-S" (which would be Command-S on Mac) to direct users to the menu item. The menu item shows its keyboard shortcut, which I believe says Ctrl-S or Cmd-S depending on the platform.
>Once a user logs in, having a link to the instructions for how to use the product would be helpful - Maybe just include a link in the docs … “after successfully logging in go to do stuff”

Added a links to the "Operations in your Session" section at the end of the document.

**Comment by martinmcclure** [comment]
Changes reviewed by Lisa and merged to "main."
