### ISSUE TITLE
Evaluator accept only works when text has been changed

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/Sparkle#37]
If you've evaluated an expression, attempts to evaluate it again will be ignored until you edit the expression to be not equal to the previously-evaluated expression. Repeated evaluation should be allowed.

**Comment by ericwinger** [comment]
I'm a little confused by the two things about the issue request. 

1.  From `SpkEvaluator>>accept` ...
If you remove these two lines, I believe the issue is resolved - at least my tests confirmed that. 
```
	self flag:
		'The command itself and menu item should be disabled instead of this test.'.
	model hasUnsavedChanges ifFalse: [ ^ self ].
```

Yet, the code & comment seem to indicate that the unsaved changes check should remain. 
Hence my confusion. 

2. My second bit of confusion is why we use Ctrl-S for the evaluator pane rather than another 
hot key?  Ctrl-S is typically reserved for saving data, say to a file. In this case it doesn't appear
we're saving anything - just opening another inspector pane.

**Comment by martinmcclure** [comment]
I don't have the code in front of me right now, so I'll comment on 1. later, but for 2. --
Ctrl-S is the standard action for "accept" in Pharo, as in accepting a method in a browser. VW also uses ctrl-S for this, but Sparkle is trying to match Pharo when it's reasonable to do so.
An accept action traditionally accepts the entirety of the text in the editing area, which is what this Sparkle action does. Other traditional Smalltalk actions like do it or inspect it only operate on the selection. There is a do it (not yet functional) in the menu for those that want to operate on the selection.

**Comment by ericwinger** [comment]
Yes, Ctrl-S is used for accepting methods in other dialects but we're not doing that here.  It seems that we could use Ctrl-E + an 'Evaluate' button.  Ctrl-S could be reserved for saving the contents of the evaluator pane to a file for later use. (Ctrl-E doesn't appear to have common usage in the Pharo browsers so it wouldn't be overloaded) 

That seems a little more intuitive to me.

**Comment by martinmcclure** [comment]
Fixed in martinDebuggerDev branch, not yet merged to development.

**Comment by martinmcclure** [comment]
This has been merged to development.
