### ISSUE TITLE
Sparkle does not support readable String viewing

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Sparkle#59]
If your evaluation returns a string, you should be able to read the string, not just examine each character.  This is functional, not aesthetic. 

![image](https://user-images.githubusercontent.com/13142166/110377629-7f13d800-8009-11eb-858a-f66d18036e96.png)

**Comment by LisaAlmarode** [comment]
There is probably a workaround. The string displays not-left-aligned (in the graphic, see 68--nimbus) but if you click on the location that the little down arrow would be if it was visible, around the 8, it turns off the expand and might display the contents.

**Comment by martinmcclure** [comment]
There are two issues here.
1) The alignment of the string preview. It should be left-aligned, so you see the first part of the string (whatever will fit) instead of the middle of the string.
2) There should be a twizzle to show the full printString (limited to, IIRC, 250000 characters), separate from the twizzle that shows and hides the field list.

**Comment by martinmcclure** [comment]
Fixed with the 3/29 merge to development.
