### ISSUE TITLE
Launcher GUI cleanup

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/Sparkle#64]
Here's the launcher as it is today:
![image](https://user-images.githubusercontent.com/2240523/113039680-c98dfd80-914c-11eb-9de2-55df7d553bd1.png)

Some minor cleanup would increase usability:

- [x] The pink color is jarring in Pharo's dark theme, which is the only theme currently supported by Sparkle
- [x] The host/port labels are a long way from their entry fields, making it hard to realize they go together
- [x]  The host and port fields run together -- it's hard to realize these are two separate fields, especially if one or both is empty.

**Comment by LisaAlmarode** [comment]
The white-on-lavender is really terrible; it's both unreadable and disorienting.  I'll add further comments:

 - [ ] "Name" was confusing if this was the stone name or a random identifier.  There's space to add "Connection Name:" which is what I think it is.

 - [ ] The tab background colors need work.  It's not clear if GCI or Direct is selected in the above example. The teal background is bright, but the gray matches the background of the pane so looks more connected=selected.  My suggestion: the selected tab color should exactly match the pane background shade of gray (a little lighter), and then the other pane could be something else which I cannot suggest since the lavender is impossible to take seriously.

 - [ ] Can the add/remove/change/cancel/connect/disconnect buttonshave bold font, and/or be slightly larger?  They are hard to find; the black entry fields are so eye-catching than the slight difference between background and buttons makes the buttons fade away.

**Comment by ericwinger** [comment]
Fixed in https://github.com/GemTalk/Sparkle/commit/0d6f2e607f91fa31c023a1fdea7bd82019455a3e

Some comments: 
- I didn't change the tab background colors. There didn't appear to be an easy way to change tab colors. 
- I don't understand why the dark theme is the only supported theme in sparkle. That seems very limiting. Regardless, it was reasonable to give the background a different color in the dark theme that was still somewhat reflective of GemTalk's purple color and so the launcher stands out from other non-gemtak pharo windows.  Color is different for light & dark themes. 
- Other text inputs that ran together were separated, as well.

**Comment by martinmcclure** [comment]
Thanks, that looks considerably better.

Being limited to the dark theme is temporary, a consequence of #41, once themes for Sparkle are developed all of the colors that are under the control of Sparkle code can be made dependent on the theme.

> GemTalk's purple color
Differentiation by color is a good idea. It wouldn't need to be purple. I don't think GemTalk has any special affinity for purple. Purple is used in some GBS-VW icons, but Jadeite doesn't use purple (and that seems fine), and our logo and website are largely purple-free.
