### ISSUE TITLE
Memory leak of launcher UI elements

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/Sparkle#90]
With all launchers closed, in an image I've been using a while:
```
Smalltalk garbageCollect.
SpkTableContainerMorph allInstances
```
Yields many instances. All seem to be the table of connection profiles in the launcher. Opening and closing the launcher results in the number of instances increasing by one.

![image](https://user-images.githubusercontent.com/2240523/116008119-d117b980-a5c7-11eb-80f6-0ac8b65a7743.png)

**Comment by ericwinger** [comment]
Fixed in: https://github.com/GemTalk/Sparkle/commit/b05eac504053de39c6b177f353ea62eb734859aa

The SpkGciConnectionPresenter and SpkInsecureConnectionPresenter announcements were getting unsubscribed in #initializeWindow: #whenClosedDo: block but subpresenters don't get sent #initializeWindow: so the unsubscribe was not happening causing a memory leak. 

Now we unsubscribe those announcements in SpkConnectionListPresenter>>initializeWindow: method which does get called.
