### ISSUE TITLE
Programmable load of Sparkle

### ISSUE THREAD

**Issue by martinmcclure** [GemTalk/Sparkle#95]
From customer:
"It would be nice if Sparkle could be loadable programmatically for example with something ike:
Metacello new
    baseline: 'Sparkle';
    repository: 'github://GemTalk/Sparkle:development';
    load

It would allow as to include sparkle in the build process of our pharo image."

**Comment by dalehenrich** [comment]
It **is** possible to programmatically load Sparkle using Metacello, but from my experience in doing that for several months in Pharo 9. It was not possible to do so AND use iceberg and even then I was not able to reliably save my work back to the disk-based git repositories (and package diff from the Monticello Browser was useless) ... if the customer only want's to load Sparkle into an image (and not do development) then it should be straightforward ... 

Let me know if that is the case (load only) and can provide the Metacello expressions that they can use (loading seems to work just fine) ... oh, and the script would assume that the git repositories have already been cloned, since Metacello does not clone git repositories...

@martinmcclure, call me, if you want to talk in more detail ...

**Comment by martinmcclure** [comment]
Thanks, @dalehenrich. The problem (for load-only) was that the post-load would fail trying to initialize the icon library. since the code as relying on it being a gitlocal:// URL. Yesterday, Kurt and I worked on a more generic solution, digging through the Metacello objects to find where it had put the repository. I'm currently reviewing that code to see if there's a less brittle way to do it.

**Comment by martinmcclure** [comment]
The code below seems to work to find the repository location so we can load the icons from it. @dalehenrich, do you know of any more direct way to get this information?
```
postload: loader package: packageSpec

	| lp adapter repo repositoryPath |
	lp := loader loaderPolicy.

	adapter := (lp repositoryMap associations
		            detect: [ :each | each key beginsWith: 'Sparkle-' ]
		            ifNone: [ 
			            ^ self
			            "If no Sparkle packages are being loaded, icons are 
					either already initialized or not needed." ])
		           value.
	repo := adapter repository.
	repositoryPath := repo location asPath.
	SpkIconLibrary loadFromPath: repositoryPath
```

**Comment by dalehenrich** [comment]
I'd be inclined to directly lookup the Sparkle repository in the system itself ... in tODE there is a way to do that, but in Pharo I don't know if there is a way to do that, especially with iceberg involved ... If you look at the Monticello Package Browser, you see that there ARE packages present, but it looks like the packages being managed by the Monticello Package Browser are all in the package cache and the `actual` location of the repository is not shown (the last time I looked was months ago, so perhaps things have changed?)... With Iceberg I don't think there is any way to access the git clone directory directly, if you don't tell Iceberg to use a disk-based clone, I don't think there is a way to access anything other than the packages  themselves since the clone isn't resident on disk anywhere ... I'm somewhat surprised that that your code works in Pharo, which proves that I'm not the right person to ask:)

**Comment by dalehenrich** [comment]
For Monticello packages (pre-github days) the only way to manage non-package data (like icon files) was to encode them as binary arrays in a method ... As i think a little more I seem to recall that  there **IS** a way to arrange for Iceberg to expose non-package files and if it does exist I would think that would be the better (more general solution).

**Comment by martinmcclure** [comment]
Thanks for the nudge. I asked the Pharo Discord, and got this lovely snippet, which has been integrated:
```
	repository := IceRepository registeredRepositoryIncludingPackage: self class package.
	repositoryPath := repository location asPath.
```

**Comment by martinmcclure** [comment]
The incantation that can now be used to load rolling-release Sparkle is
```
Metacello new
baseline: 'Sparkle';
repository: 'github://GemTalk/Sparkle:main';
load
```

**Comment by LisaAlmarode** [comment]
The incantation clones Sparkle, SparkleFFI and RSR into _pharoimage_/pharo-local/iceberg/GemTalk, and if you can find them, the git clones there can be updated (i.e. checkout a different branch) and loaded via iceberg (fetch and repair).
